apiVersion: batch/v1
kind: CronJob
metadata:
  name: posts-last-week
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.postsLastWeek.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.postsLastWeek.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
            - name: posts-last-week
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
              imagePullPolicy: Always
              env:
              - name: PYTHONUNBUFFERED
                value: "true"
              - name: MONGO_CONNECTION_STRING
                value: "{{ .Values.mongo }}"
              - name: MONGO_DB_NAME
                value: dirty
              - name: POSTS_COLLECTION_NAME
                value: posts
              - name: COMMENTS_COLLECTION_NAME
                value: comments
              - name: MEDIA_COLLECTION_NAME
                value: media
              - name: FAILURES_COLLECTION_NAME
                value: failures
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /etc/account-key/account-key.json
              volumeMounts:
              - name: account-key
                mountPath: "/etc/account-key"
                readOnly: true
              command:
                - python
                - ./app/posts.py
                - "7"
          volumes:
          - name: account-key
            secret:
              secretName: "{{ .Values.accountKeySecret }}"
          restartPolicy: Never
          {{- if (not (empty .Values.imagePullSecrets)) }}
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
            - name: {{ . | quote }}
            {{- end }}
          {{ end }}
      backoffLimit: 1