apiVersion: batch/v1
kind: CronJob
metadata:
  name: votes
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.votes.schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: {{ .Values.votes.ttlSecondsAfterFinished }}
      template:
        spec:
          containers:
            - name: votes
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
              imagePullPolicy: Always
              env:
              - name: PYTHONUNBUFFERED
                value: "true"
              - name: MONGO_CONNECTION_STRING
                value: "{{ .Values.mongo }}"
              - name: MONGO_DB_NAME
                value: dirty
              - name: POSTS_COLLECTION_NAME
                value: posts
              - name: COMMENTS_COLLECTION_NAME
                value: comments
              - name: VOTES_COLLECTION_NAME
                value: votes
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /etc/account-key/account-key.json
              - name: UID
                valueFrom:
                  secretKeyRef:
                    name: {{.Values.dirtyCredentialsSecret}}
                    key: uid
              - name: SID
                valueFrom:
                  secretKeyRef:
                    name: {{.Values.dirtyCredentialsSecret}}
                    key: sid
              volumeMounts:
              - name: account-key
                mountPath: "/etc/account-key"
                readOnly: true
              command:
                - python
                - ./app/votes.py
          volumes:
          - name: account-key
            secret:
              secretName: "{{ .Values.accountKeySecret }}"
          restartPolicy: Never
          {{- if (not (empty .Values.imagePullSecrets)) }}
          imagePullSecrets:
            {{- range .Values.imagePullSecrets }}
            - name: {{ . | quote }}
            {{- end }}
          {{ end }}
      backoffLimit: 1