image:
  repository: "romaklimenko.azurecr.io/dirty-archive"
  tag: "latest"

imagePullSecrets:
- "acr-pull"

accountKeySecret: "account-key"

mongo: "mongodb://mongodb:27017/dirty"

postsAll:
  schedule: "0 0 * * *"
  ttlSecondsAfterFinished: 43200

postsLastWeek:
  schedule: "0 * * * *"
  ttlSecondsAfterFinished: 60

media:
  schedule: "15 * * * *"
  ttlSecondsAfterFinished: 60