image:
  repository: "romaklimenko.azurecr.io/dirty-archive"
  tag: "latest"

imagePullSecrets:
  - "acr-pull"

accountKeySecret: "account-key"
dirtyCredentialsSecret: "dirty-credentials"

mongo: "mongodb://mongodb:27017/dirty"

activities:
  schedule: "0 * * * *"
  ttlSecondsAfterFinished: 3600
  skipProbabilityDenominator: 2500 # 1 - (1 - 1/2500)^(24 * 30) = 0.25

media:
  schedule: "0 * * * *"
  ttlSecondsAfterFinished: 60
